### ISSUE TITLE
A suggestion for a super-basic set

### ISSUE THREAD

**Issue by benjaminapetersen** [devonjones/openforge-tutorials#2]
Perhaps adding 1 step before the existing `basic.md` set, give a suggestion for a super, super basic set. This would be essentially just floors, or perhaps floors and doors only, intended to be the quickest way to go straight from printer to game time.  Something along the lines of this:

![Floors only set](http://dxcontent.com/DT_images/Usage_1.jpg)

The `basic.md` doc indicates about `34` total tiles, + doors and windows.  Would this work if it was simply `34` floor tiles alone?  

I imagine [the 2x2](https://www.thingiverse.com/thing:1422779) floor form this set would be sufficient?  Perhaps even splitting it out into a single thing on thingiverse (instead of a full set of many floors) to make it stupid simple to get moving.   A file for the clips may be the only addition.

**Comment by benjaminapetersen** [comment]
This is my open topic in the table top game group on thingiverse, for discussion reference. 

https://www.thingiverse.com/groups/tabletopgamers/forums/general/topic:26850#comment-1721096

**Comment by devonjones** [comment]
Good idea.  I'll start working up what I think that would need.  The walls add a lot of floor space, so it's probably more floor tiles then the current basic set.

**Comment by devonjones** [comment]
Added

**Comment by benjaminapetersen** [comment]
Awesome, thx!
