### ISSUE TITLE
Should magnet holes show through the bottom of the print?

### ISSUE THREAD

**Issue by benjaminapetersen** [devonjones/openforge-tutorials#7]
Curious about print settings, finally printing a base with the magnet holes. I stopped the print when I noticed the holes kind of show through the bottom.  It looks like the printer isn't quite sure if it wants a flat bottom layer or not. See attached image.

This is from a LulzBot Mini.

![openforge_failed_magnet_holes](https://user-images.githubusercontent.com/280512/35824184-1187f69c-0a80-11e8-841c-7c8dbcda64e2.jpg)

**Comment by benjaminapetersen** [comment]
I let this one finish, bottom def seems odd?

![img_20180207_195012](https://user-images.githubusercontent.com/280512/35950678-b66b2e1a-0c45-11e8-9f5d-763faef8d4af.jpg)

**Comment by devonjones** [comment]
Yeah, that's correct.  The holes are so you can push a magnet that's stuck out with a paperclip.  I added it so that if you push a magnet in and found out that it won't rotate, you can actually get it back out again.

**Comment by devonjones** [comment]
Though I will say, it looks like your printer is having problems joining that area with the rest of the print.  You can probably fix that by changing your shells setting in your slicer.

**Comment by benjaminapetersen** [comment]
Aaah, that makes sense! I saw on a YouTube video that there are supposed to be tiny holes for what you mentioned.  So it does seem my printer is struggling, perhaps with how thin the base layer is or something.  Thx, I'll look into that.
